import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { AppSidebar } from "@/components/layout/app-sidebar";
import { Header } from "@/components/layout/header";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";
import { CartStoreProvider } from "@/features/cart/providers/cart-store-provider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id">
      <body className={`${inter.className}`}>
        <SidebarProvider defaultOpen={false}>
          <AppSidebar />
          <CartStoreProvider>
            <div className="flex w-full flex-col">
              <Header />
              <main className="w-full">{children}</main>
            </div>
          </CartStoreProvider>
        </SidebarProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}
